### ISSUE TITLE
Problems with downloadUSDLogfile

### ISSUE THREAD

**Issue by katzuv** [whoenig/crazyflie_tools#1]
Hello,
When trying to run `rosrun crazyflie_tools downloadUSDLogfile` we get the following error:
```
Could not find USD deck logging variables!
```
What is triggering this error message? I couldn't really understand from the C++ source file.

Notes:
- The CFClient's console doesn't say there are problem with the μSD card deck and/or logging on it
- if I connect the μSD card to my computer, I can see there are log files being generated on the card.

Thank you!

**Comment by whoenig** [comment]
It means that either `deck.bcUSD` or `usd.logging` parameters are not part of your firmware image. Are you running the latest firmware? What does `rosrun crazyflie_tools listParams` report?

**Comment by katzuv** [comment]
Oh, OK! You are right, we were using an older firmware (before bitcraze/crazyflie-firmware@0d305b2) and didn't realize the download wouldn't work without your changes. Thank you for your fast response. 
Do you know if it's possible to download the log file with the Crazyflie Python API? Or is it only possible through crazyflie_tools?
Also, my I suggest to make this error message more clear. Also, I think that the `No matching USB Device with devid = 0 found!` error message could be clearer. I can open a quick PR and change those if you'd like to.

**Comment by whoenig** [comment]
To my knowledge, the Python API does not have the feature yet. However, this just uses the memory subsystem, which is well supported in the Python API, so it would likely just be a couple of lines to add it.

Agreed with the error messages. A PR would be very welcome - Thanks!

**Comment by katzuv** [comment]
Thank you for your answer.
I'll try to work on the PR soon.

**Comment by katzuv** [comment]
Hey @whoenig, please see my PRs at https://github.com/whoenig/crazyflie_tools/pull/2 and https://github.com/whoenig/crazyflie_cpp/pull/11.

**Comment by whoenig** [comment]
Thanks Dan.

**Comment by katzuv** [comment]
Hello, @whoenig once again.
So we were trying the `downloadUSDLogfile` once again and we managed to download a log from the microSD card. The file is attached [here](https://github.com/whoenig/crazyflie_tools/files/3923998/output.log).
We are having a couple of issues with this tool:
1) We can't decode the log files successfully with the `decode` function from [here](https://github.com/bitcraze/crazyflie-firmware/blob/master/tools/usdlog/CF_functions.py#L13-L79). Specifically, we are getting this error:
```python
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-18-49698fa3e195> in <module>
----> 1 decode('output.log')

<ipython-input-14-7cf8b06407e7> in decode(filName)
     42         offset += 1
     43         for ii in range(setNumber[0]):
---> 44             setCon[idx:idx+setWidth[0]] = np.array(struct.unpack(fmtStr, filCon[offset:setBytes+offset]))
     45             offset += setBytes
     46             idx += setWidth[0]

error: unpack requires a buffer of 28 bytes
```
Decoding a file taken directly from the microSD card (through a computer) is no problem,
2) After the tool finishes downloading the log file from the Crazyflie, the drone reboots for some reason and then doesn't pass a self-test (five quick red flashes).
3) It takes some time to download the log file, but I guess this is expected. However, our files are not too big.
Also, at one time the file was medium-size and I went away for a few minutes. When I returned, I saw a "timeout" error message, and the Crazyflie was "stuck" (only one constant blue LED).
4) A question: Where do the files get downloaded? To my current working directory?

Many thanks!

**Comment by whoenig** [comment]
Which firmware version are you using? It sounds like some of your issues might be related to each other. In general, I have not seen any data corruption (and I use it on fairly big files) if the download is successful (i.e., no "timeout" is reported).

1. This looks like your data file is corrupted. During the download, was there any error?
2. This is not normal. Are there any asserts reported for the crash? You might be hitting a variant of https://github.com/USC-ACTLab/crazyswarm/issues/182.
3. Yes, it is pretty slow. About 5kb/s for me. If you run it with `--verbose` it will print some statistics. This is a limitation of the radio and protocol.
4. Your current working directory. In the future, i plan to add a `-o` switch so one has to specify the output file/folder.

**Comment by katzuv** [comment]
Hey,
1. No, no errors. Only this expected output (when running with the `-v` flag):
```text
File is 25766 bytes.
read 25766 in 3.0537 s. (8437.62 B/s).
read 25766
```
2. When I connect to the drone with the cfclient, I see these two lines at the end of the log:
```text
SYS: The system resumed after watchdog timeout [WARNING]
SYS: Assert failed at src/modules/src/crtp.c:186
```
The two aforementioned problems persist also when connecting only the microSD card Deck, and using the stock Crazyflie release from September ([`v2019.09`](https://github.com/bitcraze/crazyflie-firmware/releases/tag/2019.09)).

This is similar to the error described in USC-ACTLab/crazyswarm#182. However, I tried your solution, removing the assert line in `crtp.c`, and it was "two birds with one stone": It stopped the reboot, and the log is no longer corrupted :grinning:.
So first, thank you! Second, are you aware of any issues that might arise because of the removal of that assert?
Thanks!

**Comment by whoenig** [comment]
Thanks for reporting back - this is very interesting! I am not sure where this file corruption comes from. If you use ROS, there should be no side effects from removing the assert.

**Comment by katzuv** [comment]
Thank you. We thought about using the Crazyflie parameter system to only temporarily disable this assert when downloading remotely, just to be sure we don't break anything.
